version: 2.1

orbs:
    node: circleci/node@5.1.0
    ssh: credijusto/ssh@0.5.2
workflows:
    release:
        jobs:
            -   node/run:
                    name: build
                    npm-run: build
                    pre-steps:
                        -   name: Setup Golang
                            run:
                                command: >
                                    sudo apt-get update;
                                    sudo apt-get install bison;
                                    bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer);
                                    source ~/.gvm/scripts/gvm;
                                    gvm install go1.4 -B;
                                    gvm use go1.4 --default;
                                    gvm install go1.8 -B;
                                    gvm use go1.8 --default;
                                    VERSION=0.28.1;
                                    TINYGO="tinygo_${VERSION}_amd64.deb";
                                    wget https://github.com/tinygo-org/tinygo/releases/download/v$VERSION/$TINYGO;
                                    sudo dpkg -i $TINYGO && rm $TINYGO;
                    setup:
                        - run:
                              name: Fetch Wasm Deps
                              command: >
                                  cd src/golang;
                                  go get;


                    post-steps:
                        -   persist_to_workspace:
                                root: .
                                paths:
                                    - lib/

                    filters:
                        branches:
                            only:
                                - master
                                - develop
                                - /^develop-.*$/
            -   node/run:
                    name: release
                    npm-run: semantic-release
                    requires:
                        - build
                    filters:
                        branches:
                            only:
                                - master
                                - develop
                                - /^develop-.*$/

                    context:
                        - publish
                    setup:
                        -  attach_workspace:
                            at: ./
                        -   add_ssh_keys:
                                fingerprints:
                                    - "47:cf:a1:17:d9:81:8e:c5:51:e5:53:c8:33:e4:33:b9"
                        -   ssh/ssh-add-host:
                                host_url: GITEA_HOST
