name: Build/Publish

on:
    push:
        branches:
            - master
            - develop
            - develop-*
    workflow_dispatch:
        inputs:
            debug_enabled:
                description: debug_enabled
                type: boolean
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Use Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 18.x
                    cache: 'npm'
            -  name: Setup Golang
               uses: actions/setup-go@v4
               with:
                 go-version: 1.19
            -   name: Setup Golang
                run: |
                    VERSION=0.28.1;
                    TINYGO="tinygo_${VERSION}_amd64.deb";
                    wget -q https://github.com/tinygo-org/tinygo/releases/download/v$VERSION/$TINYGO;
                    sudo dpkg -i $TINYGO && rm $TINYGO;
            -   name: Fetch Wasm Deps
                run: cd src/golang && go get
            -   run: npm ci
            -   run: npm run build --if-present
            -   name: Install SSH key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.GITEA_SSH_KEY }}
                    known_hosts: ${{ secrets.GITEA_KNOWN_HOST }}

            -   name: Publish
                run: npm run semantic-release
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            -   name: Setup tmate session
                uses: mxschmitt/action-tmate@v3
                if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled && failure() }}
                with:
                    limit-access-to-actor: true
